# - name: add ssh key for rog
#   authorized_key:
#   user: root
#   key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXA7s9ThYPDxLdB6WbT36uNLeBJX2tAZbBuPT6XpDuobtw8VWq7qo7XtPxoaDV7WJx/+iB+0L4TGSAn5PffzhL4DQXz+JV7AfJz/QDv/GWLc9RyGeSQX1mIo9IyitoYtwD9qs3is2q2QJ2Ey6PMRluC6m5DHDw1/9R0psgJ4uXR4KiOl5e9j/xYJVQAiN/hzrRq9uX7rZekhw9vacMpdf+jQsbRQvvIFylOBL7lw+b3ZMOo32WKUSWiM1BoJ3OEAUycpzeyU+5MGb0/vSD1YheYRrXLuUQqGOLgkw7ZSaLtiXuTep/CYe8TDZS40LyUwJtHr8Xw0r58cePPNdnjLk7Pi+6dEuM+X8S52RjjsnOh5ruRtnMUsn2Ox/OIZcnA7C985OacIm5Z+tEGpl0Jj2VsZ6DxPl/vUQNuoFFS+mS37It31OeIvZ9Bst86qt2xV5YcxpYXbRQ5D3MBevDSpB6Xwaq5he+u7Z/+7JIkofsZwHZ5jm3QaphCsYB3AqC5rk= user@rog"
- name: Installing sudo, zip
  tags: base
  apt:
    name:
      - sudo
      - zip
- name: Copying the sudoers files
  tags: base
  copy:
    src: sudo
    dest: /etc/sudoers.d/
    force: yes
